### ISSUE TITLE
use in-memory filesystem for tests

### ISSUE THREAD

**Issue by falafeljan** [ununu-p2p/als-parser#12]
we currently write to pseudo-random directory (`/private/tmp/...`) when running tests. this fails for our CI and isn't a clean solution when considering reproducible test environments.

my proposal:
* use `memfs` (https://github.com/streamich/memfs) and mock the `fs` dependency with `rewire` (https://github.com/jhnns/rewire)
* simply mount the mock directory into the memory fs and run tests as usual

i'm happy to take on this once i have some spare time. should solve #9.

**Comment by shresthagrawal** [comment]
Awesome! Looking forward for that
